services:
  db:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: elestio/pgadmin:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: always

  nginx_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: nginx
    container_name: nginx_backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:80
    depends_on:
      - backend
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    restart: always
