services:
    db:
        container_name: postgres
        image: postgres:alpine
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PW}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        restart: always

    pgadmin:
        container_name: pgadmin
        image: elestio/pgadmin:latest
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
        ports:
            - "5050:80"
        restart: always

    backend:
        container_name: backend
        image: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: development
        volumes:
            - ./backend:/app
        depends_on:
            - db
        restart: always

    nginx_backend:
        container_name: nginx_backend
        image: nginx_backend
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: nginx
        volumes:
            - ./backend:/app
        ports:
            - 5025:80
        depends_on:
            - backend
        restart: always

    frontend:
        container_name: frontend
        image: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        restart: always
